"""
ISO Codes (Acquierer Response Code) dictionary
"""
ISO_CODES = {
    "00": ["APROBADA"],
    "01": ["LLAME EMISOR"],
    "02": ["LLAME EMISOR"],
    "03": ["COMERCIO INVALIDO"],
    "04": ["RETENER TARJETA"],
    "05": ["TRANSACCION INVALIDA"],
    "06": ["REINTENTE"],
    "07": ["Llame al emisor.", "Declinada."],
    "08": ["Solicite identificación al cliente."],
    "09": ["Transaccion duplicada."],
    "11": ["Aprobada (VIP)"],
    "12": ["TRANSACCION NO PERMITIDA"],
    "13": ["TRANSACCION NO PERMITIDA"],
    "14": ["TARJETA INVALIDA"],
    "21": ["Transaccion no encontrada o ya cancelada."],
    "31": ["TRANSACCION NO PERMITIDA"],
    "33": ["Tarjeta expirada."],
    "34": ["Se sospecha fraude, detener tarjeta."],
    "36": ["RETENER TARJETA"],
    "37": ["Llame al emisor."],
    "38": ["Numero de intentos de NIP excedido."],
    "39": ["Tarjeta rechazada."],
    "41": ["RETENER TARJETA"],
    "43": ["RETENER TARJETA"],
    "51": ["FONDOS INSUFICIENTES"],
    "54": ["TARJETA VENCIDA"],
    "55": ["PIN INVALIDO"],
    "56": ["TARJETA INVALIDA"],
    "57": ["PAGO DIFERIDO NO PERMITIDO"],
    "61": ["LIMITE EXCEDIDO"],
    "62": ["TRANSACCION NO PERMITIDA"],
    "65": ["LIMITE EXCEDIDO"],
    "68": ["REINTENTE"],
    "76": ["Aprobado country club."],
    "77": ["Requiere identificacion."],
    "78": ["Aprobado ciego."],
    "79": ["Aprobado administrativamente."],
    "80": ["Approved national negative file hit OK."],
    "81": ["Aprobado comercial."],
    "82": ["TARJETA INVALIDA"],
    "83": ["TARJETA INVALIDA"],
    "87": ["TARJETA INVALIDA"],
    "89": ["TIPO DE PLAN / PLAZO INVALIDO"],
    "94": ["TRANSACCION DUPLICADA"],
    "N2": ["AUTORIZACIONES EXCEDIDAS"],
    "N3": ["Límite de devoluciones online alcanzado."],
    "N4": ["Límite de devoluciones offline alcanzado."],
    "N5": ["TRANSACCION NO PERMITIDA"],
    "N6": ["Límite de devoluciones alcanzado."],
    "N7": ["TARJETA INVALIDA"],
    "N9": ["Maximo numero de devoluciones alcanzado."],
    "O3": ["Delincuente."],
    "O4": ["LIMITE EXCEDIDO"],
    "O5": ["Se requiere el NIP."],
    "O6": ["TARJETA INVALIDA"],
    "O8": ["TARJETA INVALIDA"],
    "P1": ["TRANSACCION NO PERMITIDA"],
    "P9": ["LIMITE EXCEDIDO"],
    "Q1": ["TARJETA INVALIDA"],
    "Q7": ["Importe maximo superado."],
    "R8": ["Tarjeta en lista negra."],
    "S5": ["Devolución aprobada, archivo del cliente no actualizado."],
    "S6": ["Devolución aprobada, archivo del cliente no actualizado, adquirente no encontrado."],
    "S7": ["Devolución aceptada, destino incorrecto."],
    "S9": ["No se puede verificar el NIP."],
    "T1": ["Cantidad invalida."],
    "T2": ["ERROR EN TERMINAL"],
    "T3": ["TRANSACCIÓN NO PERMITIDA"],
    "T5": ["TARJETA SIN ACTIVAR"],
    "T7": ["Límite de retiros diarios excedido."],
    "T9": ["MONEDA INVALIDA"],
    "XX": ["DENEGADA ONLINE"]
}