"""
ISO Codes (Acquierer Response Code) dictionary
"""
ISO_CODES = {
    "00": ["APROBADA"],
    "01": ["LLAME EMISOR"],
    "02": ["LLAME EMISOR"],
    "03": ["COMERCIO INVALIDO"],
    "04": ["RETENER TARJETA"],
    "05": ["TRANSACCION INVALIDA"],
    "06": ["REINTENTE"],
    "07": ["Llame al emisor.", "Declinada."],
    "08": ["Solicite identificación al cliente."],
    "09": ["Transaccion duplicada."],
    "11": ["Aprobada (VIP)"],
    "12": ["TRANSACCION NO PERMITIDA"],
    "13": ["TRANSACCION NO PERMITIDA"],
    "14": ["TARJETA INVALIDA"],
    "15": ["No existe el emisor."],
    "21": ["Transaccion no encontrada o ya cancelada."],
    "30": ["ERROR DE FORMATO"],
    "31": ["TRANSACCION NO PERMITIDA"],
    "33": ["Tarjeta expirada."],
    "34": ["Se sospecha fraude, detener tarjeta."],
    "35": ["Tienda contacte al adquirente."],
    "36": ["RETENER TARJETA"],
    "37": ["Llame al emisor."],
    "38": ["Numero de intentos de NIP excedido."],
    "39": ["Tarjeta rechazada."],
    "41": ["RETENER TARJETA"],
    "42": ["Cargo denegado (956)."],
    "43": ["RETENER TARJETA"],
    "45": ["NA"],
    "51": ["FONDOS INSUFICIENTES"],
    "54": ["TARJETA VENCIDA"],
    "55": ["PIN INVALIDO"],
    "56": ["TARJETA INVALIDA"],
    "57": ["PAGO DIFERIDO NO PERMITIDO"],
    "58": ["Transaccion no permitida a la terminal."],
    "61": ["LIMITE EXCEDIDO"],
    "62": ["TRANSACCION NO PERMITIDA"],
    "65": ["LIMITE EXCEDIDO"],
    "68": ["REINTENTE"],
    "70": ["Error descifrando track2"],
    "75": ["PIN INVALIDO/EXCEDIDO"],
    "76": ["Aprobado country club."],
    "77": ["Requiere identificacion."],
    "78": ["Aprobado ciego."],
    "79": ["Aprobado administrativamente."],
    "80": ["Approved national negative file hit OK."],
    "81": ["Aprobado comercial."],
    "82": ["TARJETA INVALIDA"],
    "83": ["TARJETA INVALIDA"],
    "84": ["C R NO PERMITIDO POR TH"],
    "85": ["PBF Error de actualizacion."],
    "86": ["Tipo de autorización invalido."],
    "87": ["TARJETA INVALIDA"],
    "88": ["Error PTLF."],
    "89": ["TIPO DE PLAN / PLAZO INVALIDO"],
    "90": ["Corte en proceso, la transaccion podra enviarse nuevamente en unos minutos."],
    "91": ["Error en el emisor."],
    "92": ["No se puede encontrar la institución financiera para enlace."],
    "94": ["TRANSACCION DUPLICADA"],
    "96": ["Error del sistema."],
    "N0": ["REINTENTE"],
    "N1": ["Longitud del PAN erronea."],
    "N2": ["AUTORIZACIONES EXCEDIDAS"],
    "N3": ["Límite de devoluciones online alcanzado."],
    "N4": ["Límite de devoluciones offline alcanzado."],
    "N5": ["TRANSACCION NO PERMITIDA"],
    "N6": ["Límite de devoluciones alcanzado."],
    "N7": ["TARJETA INVALIDA"],
    "N8": ["Límite de piso alcanzado."],
    "N9": ["Maximo numero de devoluciones alcanzado."],
    "O0": ["Archivo referido lleno."],
    "O1": ["Problema con el archivo NEG."],
    "O2": ["Avance inferior al mínimo."],
    "O3": ["Delincuente."],
    "O4": ["LIMITE EXCEDIDO"],
    "O5": ["Se requiere el NIP."],
    "O6": ["TARJETA INVALIDA"],
    "O7": ["Post forzado."],
    "O8": ["TARJETA INVALIDA"],
    "O9": ["Problema con el archivo NEG."],
    "P0": ["Problema CAF."],
    "P1": ["TRANSACCION NO PERMITIDA"],
    "P2": ["CAPF No encontrado."],
    "P4": ["Numero de veces utilizados."],
    "P8": ["Se requiere tarjeta administrativa."],
    "P9": ["LIMITE EXCEDIDO"],
    "Q0": ["Fecha de transacción invalida."],
    "Q1": ["TARJETA INVALIDA"],
    "Q2": ["Codigo de transacción invalido."],
    "Q5": ["Numero de afiliación invalido."],
    "Q7": ["Importe maximo superado."],
    "Q8": ["Tarjeta administrativa no encontrada."],
    "Q9": ["Tarjeta administrativa no permitida."],
    "R0": ["Aprobo la solicitud administrativa realizada en la ventana."],
    "R1": ["Aprobo la solicitud administrativa realizada fuera de la ventana."],
    "R2": ["Aprobo la solicitud administrativa realizada en cualquier momento."],
    "R3": ["Devolución de cargo del cliente archivo actualizado."],
    "R4": ["Devolución de cargo del cliente archivo actualizado, adquirente no encontrado."],
    "R5": ["Devolución, numero de prefijo incorrecto."],
    "R6": ["Devolución, codigo de respuesta incorrecto o configuración CPF incorrecta."],
    "R7": ["Transacciones administrativas no soportadas."],
    "R8": ["Tarjeta en lista negra."],
    "S4": ["PTFL completo."],
    "S5": ["Devolución aprobada, archivo del cliente no actualizado."],
    "S6": ["Devolución aprobada, archivo del cliente no actualizado, adquirente no encontrado."],
    "S7": ["Devolución aceptada, destino incorrecto."],
    "S8": ["Problema con el archivo ADMN."],
    "S9": ["No se puede verificar el NIP."],
    "T1": ["Cantidad invalida."],
    "T2": ["ERROR EN TERMINAL"],
    "T3": ["TRANSACCIÓN NO PERMITIDA"],
    "T5": ["TARJETA SIN ACTIVAR"],
    "T6": ["UAF incorrecto."],
    "T7": ["Límite de retiros diarios excedido."],
    "T9": ["MONEDA INVALIDA"],
    "XX": ["DENEGADA ONLINE"]
}